export const images = [
	"images/img-2.jpg",
	"images/img-1.jpg",
	"images/img-3.jpg",
	"images/img-4.jpg",
	"images/img-5.jpg",
	"images/img-6.jpg",
	"images/img-7.jpg",
	"images/img-8.jpg",
	"images/img-9.jpg",
	"images/img-10.jpg",
	"images/img-12.jpg",
];
// export const images = [
// 	{url: "images/img-1.jpg"},
// 	{url: "images/img-2.jpg"},
// 	{url: "images/img-3.jpg"},
// 	{url: "images/img-4.jpg"},
// 	{url: "images/img-5.jpg"},
// 	{url: "images/img-6.jpg"},
// 	{url: "images/img-7.jpg"},
// 	{url: "images/img-8.jpg"},
// 	{url: "images/img-9.jpg"},
// 	{url: "images/img-10.jpg"},
// 	{url: "images/img-11.jpg"},
// 	{url: "images/img-12.jpg"},
// 	// {url: "images/img-13.jpg"},
// ];
